steps:
  # Install dependencies
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['ci']
    
  # Build the application
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build']
    
  # Deploy to Firebase App Hosting
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud config set project advocate-empower
        firebase deploy --only apphosting

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '1200s'